# Generated by Django 5.2.9 on 2025-12-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
